### ISSUE TITLE
BoxPlots

### ISSUE THREAD

**Issue by mkranii** [hydro-lab/wind-power#9]
How can I get all three boxplots onto one graph/figure?

https://github.com/hydro-lab/wind-power/blob/main/boxplots

**Comment by dmkahler** [comment]
Current push contains a suggested edit.  Your original plots remain.  Note, line 38 (the command "factor") is where I set the order - the default is alphabetical.  I also added line 43, "ylab" that includes tex commands to place the subscript 2 in CO2 and italicized the "eq".  Please edit these as you need.

Most importantly, I included a "ylim" online 44.  This produces a nice figure that emphasizes the difference between the sources.  Since it cuts off two outliers, you should disclose those in the figure caption.  The values are 2.27 and 2.92.  An outlier is one that is outside 1.5*IQR from the 25th or 75th percentiles.
